### ISSUE TITLE
Related to tooltip

### ISSUE THREAD

**Issue by harsee4all** [filipetedim/angular-rating#8]
Hi, I want to learn about the tooltip such as we got 5 star and I want to give them effect on hover as tittle show up for first star as very poor and 2 star as poor and so on till 5star as Very  Good to appear as tooltip. 
how can i achieve that?

**Comment by filipetedim** [comment]
Hey. Sadly my plugin is **_not_** prepared to do this. There is however an alternative. You can use jQuery to get all the stars icons, and then you can assign a title to them in the correct order that you want. If you have only 5 stars, create 5 different ratings, I put 10 here because my example has 10 stars (5 but each is a half star).

You need to wrap it inside a `$timeout` so that this code gets added **after** your `ng-repeat` finishes rendering. The order of the titles will be from worst to best.
You can check the code example here: https://jsfiddle.net/0595783t/97/

```javascript
$timeout(function() {
    var titleGroup = [
        'Extremely poor', 
        'Very poor', 
        'Poor', 
        'Below medium', 
        'At medium',
        'Above medium', 
        'Almost good', 
        'Good', 
        'Very good', 
        'Extremely good'
    ];

    $('.angular-rating-icons>li').each(function(i) {
        $(this).attr('title', titleGroup[i]);
    });
});
```

If you still want to have 5 stars, but using half, and you want each full star to have the same title, just repeat the title every 2 times, [like in this example](https://jsfiddle.net/0595783t/98/):
```javascript
var titleGroup = [
    'Very poor',
    'Very poor',
    'Poor',
    'Poor',
    'Medium',
    'Medium',
    'Good',
    'Good',
    'Very good',
    'Very good',
];
```

You can also use `angular.element()` for the same result, but jQuery was faster to make an example.

**Comment by harsee4all** [comment]
thank you, yea it will work for my code. and your plugin is really good.
